"""2

Revision ID: 5208404b5b48
Revises: 72f8f2d406df
Create Date: 2026-01-16 13:59:30.312555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5208404b5b48'
down_revision: Union[str, None] = '72f8f2d406df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('name_pc', sa.String(length=255), nullable=False))
    op.add_column('agents', sa.Column('user_name', sa.String(length=255), nullable=False))
    op.add_column('agents', sa.Column('ip_addr', sa.String(length=15), nullable=False))
    op.drop_column('agents', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('agents', 'ip_addr')
    op.drop_column('agents', 'user_name')
    op.drop_column('agents', 'name_pc')
    # ### end Alembic commands ###
