"""agent + Null

Revision ID: 8b820db7e71e
Revises: d8727d63978b
Create Date: 2026-01-16 21:20:14.336190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b820db7e71e'
down_revision: Union[str, None] = 'd8727d63978b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'user_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('agents', 'ip_addr',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'ip_addr',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('agents', 'user_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
